<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;
use App\Models\KategoriYayinTipiFieldDependency;

class PropertyTypeDefaultFieldsSeeder extends Seeder
{
    public function run(): void
    {
        if (!Schema::hasTable('kategori_yayin_tipi_field_dependencies')) {
            return;
        }

        $fields = [
            [ 'kategori_slug' => 'konut', 'yayin_tipi' => 'Yazlık Kiralık', 'field_slug' => 'havuz', 'field_name' => 'Havuz', 'field_type' => 'boolean', 'field_category' => 'Olanaklar', 'field_icon' => '🏊', 'status' => true, 'required' => false, 'display_order' => 16, 'ai_auto_fill' => false, 'ai_suggestion' => false, 'searchable' => false, 'show_in_card' => true ],
            [ 'kategori_slug' => 'konut', 'yayin_tipi' => 'Yazlık Kiralık', 'field_slug' => 'jakuzi', 'field_name' => 'Jakuzi', 'field_type' => 'boolean', 'field_category' => 'Olanaklar', 'field_icon' => '🛁', 'status' => true, 'required' => false, 'display_order' => 17, 'ai_auto_fill' => false, 'ai_suggestion' => false, 'searchable' => false, 'show_in_card' => true ],
            [ 'kategori_slug' => 'konut', 'yayin_tipi' => 'Yazlık Kiralık', 'field_slug' => 'klima', 'field_name' => 'Klima', 'field_type' => 'boolean', 'field_category' => 'Genel Özellikler', 'field_icon' => '❄️', 'status' => true, 'required' => false, 'display_order' => 18, 'ai_auto_fill' => false, 'ai_suggestion' => false, 'searchable' => false, 'show_in_card' => true ],
            [ 'kategori_slug' => 'konut', 'yayin_tipi' => 'Yazlık Kiralık', 'field_slug' => 'barbeku', 'field_name' => 'Barbekü', 'field_type' => 'boolean', 'field_category' => 'Olanaklar', 'field_icon' => '🍖', 'status' => true, 'required' => false, 'display_order' => 19, 'ai_auto_fill' => false, 'ai_suggestion' => false, 'searchable' => false, 'show_in_card' => true ],
            [ 'kategori_slug' => 'konut', 'yayin_tipi' => 'Yazlık Kiralık', 'field_slug' => 'teras', 'field_name' => 'Geniş Teras', 'field_type' => 'boolean', 'field_category' => 'Genel Özellikler', 'field_icon' => '🛋️', 'status' => true, 'required' => false, 'display_order' => 20, 'ai_auto_fill' => false, 'ai_suggestion' => false, 'searchable' => false, 'show_in_card' => true ],
            [ 'kategori_slug' => 'konut', 'yayin_tipi' => 'Yazlık Kiralık', 'field_slug' => 'deniz_manzarasi', 'field_name' => 'Deniz Manzarası', 'field_type' => 'boolean', 'field_category' => 'Genel Özellikler', 'field_icon' => '🌊', 'status' => true, 'required' => false, 'display_order' => 21, 'ai_auto_fill' => false, 'ai_suggestion' => false, 'searchable' => false, 'show_in_card' => true ],
            [ 'kategori_slug' => 'konut', 'yayin_tipi' => 'Yazlık Kiralık', 'field_slug' => 'plaja_yakin', 'field_name' => 'Plaja Yakın', 'field_type' => 'boolean', 'field_category' => 'Genel Özellikler', 'field_icon' => '🏖️', 'status' => true, 'required' => false, 'display_order' => 22, 'ai_auto_fill' => false, 'ai_suggestion' => false, 'searchable' => false, 'show_in_card' => true ],
            [ 'kategori_slug' => 'konut', 'yayin_tipi' => 'Yazlık Kiralık', 'field_slug' => 'min_gece', 'field_name' => 'Minimum Gece Sayısı', 'field_type' => 'number', 'field_category' => 'Genel Özellikler', 'field_icon' => '🕒', 'status' => true, 'required' => false, 'display_order' => 23, 'ai_auto_fill' => false, 'ai_suggestion' => false, 'searchable' => false, 'show_in_card' => false ],
            [ 'kategori_slug' => 'konut', 'yayin_tipi' => 'Yazlık Kiralık', 'field_slug' => 'temizlik_ucreti', 'field_name' => 'Temizlik Ücreti', 'field_type' => 'price', 'field_category' => 'Genel Özellikler', 'field_icon' => '🧼', 'status' => true, 'required' => false, 'display_order' => 24, 'ai_auto_fill' => false, 'ai_suggestion' => false, 'searchable' => false, 'show_in_card' => false ],
            // Yazlık kategori slug için aynı set
            [ 'kategori_slug' => 'yazlik', 'yayin_tipi' => 'Yazlık Kiralık', 'field_slug' => 'havuz', 'field_name' => 'Havuz', 'field_type' => 'boolean', 'field_category' => 'Olanaklar', 'field_icon' => '🏊', 'status' => true, 'required' => false, 'display_order' => 16, 'ai_auto_fill' => false, 'ai_suggestion' => false, 'searchable' => false, 'show_in_card' => true ],
            [ 'kategori_slug' => 'yazlik', 'yayin_tipi' => 'Yazlık Kiralık', 'field_slug' => 'jakuzi', 'field_name' => 'Jakuzi', 'field_type' => 'boolean', 'field_category' => 'Olanaklar', 'field_icon' => '🛁', 'status' => true, 'required' => false, 'display_order' => 17, 'ai_auto_fill' => false, 'ai_suggestion' => false, 'searchable' => false, 'show_in_card' => true ],
            [ 'kategori_slug' => 'yazlik', 'yayin_tipi' => 'Yazlık Kiralık', 'field_slug' => 'klima', 'field_name' => 'Klima', 'field_type' => 'boolean', 'field_category' => 'Genel Özellikler', 'field_icon' => '❄️', 'status' => true, 'required' => false, 'display_order' => 18, 'ai_auto_fill' => false, 'ai_suggestion' => false, 'searchable' => false, 'show_in_card' => true ],
            [ 'kategori_slug' => 'yazlik', 'yayin_tipi' => 'Yazlık Kiralık', 'field_slug' => 'barbeku', 'field_name' => 'Barbekü', 'field_type' => 'boolean', 'field_category' => 'Olanaklar', 'field_icon' => '🍖', 'status' => true, 'required' => false, 'display_order' => 19, 'ai_auto_fill' => false, 'ai_suggestion' => false, 'searchable' => false, 'show_in_card' => true ],
            [ 'kategori_slug' => 'yazlik', 'yayin_tipi' => 'Yazlık Kiralık', 'field_slug' => 'teras', 'field_name' => 'Geniş Teras', 'field_type' => 'boolean', 'field_category' => 'Genel Özellikler', 'field_icon' => '🛋️', 'status' => true, 'required' => false, 'display_order' => 20, 'ai_auto_fill' => false, 'ai_suggestion' => false, 'searchable' => false, 'show_in_card' => true ],
            [ 'kategori_slug' => 'yazlik', 'yayin_tipi' => 'Yazlık Kiralık', 'field_slug' => 'deniz_manzarasi', 'field_name' => 'Deniz Manzarası', 'field_type' => 'boolean', 'field_category' => 'Genel Özellikler', 'field_icon' => '🌊', 'status' => true, 'required' => false, 'display_order' => 21, 'ai_auto_fill' => false, 'ai_suggestion' => false, 'searchable' => false, 'show_in_card' => true ],
            [ 'kategori_slug' => 'yazlik', 'yayin_tipi' => 'Yazlık Kiralık', 'field_slug' => 'plaja_yakin', 'field_name' => 'Plaja Yakın', 'field_type' => 'boolean', 'field_category' => 'Genel Özellikler', 'field_icon' => '🏖️', 'status' => true, 'required' => false, 'display_order' => 22, 'ai_auto_fill' => false, 'ai_suggestion' => false, 'searchable' => false, 'show_in_card' => true ],
            [ 'kategori_slug' => 'yazlik', 'yayin_tipi' => 'Yazlık Kiralık', 'field_slug' => 'min_gece', 'field_name' => 'Minimum Gece Sayısı', 'field_type' => 'number', 'field_category' => 'Genel Özellikler', 'field_icon' => '🕒', 'status' => true, 'required' => false, 'display_order' => 23, 'ai_auto_fill' => false, 'ai_suggestion' => false, 'searchable' => false, 'show_in_card' => false ],
            [ 'kategori_slug' => 'yazlik', 'yayin_tipi' => 'Yazlık Kiralık', 'field_slug' => 'temizlik_ucreti', 'field_name' => 'Temizlik Ücreti', 'field_type' => 'price', 'field_category' => 'Genel Özellikler', 'field_icon' => '🧼', 'status' => true, 'required' => false, 'display_order' => 24, 'ai_auto_fill' => false, 'ai_suggestion' => false, 'searchable' => false, 'show_in_card' => false ],
            [ 'kategori_slug' => 'konut', 'yayin_tipi' => 'Satılık', 'field_slug' => 'balkon', 'field_name' => 'Balkon', 'field_type' => 'boolean', 'field_category' => 'Genel Özellikler', 'field_icon' => '🛗', 'status' => true, 'required' => false, 'display_order' => 10, 'ai_auto_fill' => false, 'ai_suggestion' => false, 'searchable' => false, 'show_in_card' => true ],
            [ 'kategori_slug' => 'konut', 'yayin_tipi' => 'Satılık', 'field_slug' => 'esyalı', 'field_name' => 'Eşyalı', 'field_type' => 'boolean', 'field_category' => 'Genel Özellikler', 'field_icon' => '🧳', 'status' => true, 'required' => false, 'display_order' => 11, 'ai_auto_fill' => false, 'ai_suggestion' => false, 'searchable' => false, 'show_in_card' => true ],
            [ 'kategori_slug' => 'konut', 'yayin_tipi' => 'Satılık', 'field_slug' => 'otopark', 'field_name' => 'Otopark', 'field_type' => 'boolean', 'field_category' => 'Genel Özellikler', 'field_icon' => '🅿️', 'status' => true, 'required' => false, 'display_order' => 12, 'ai_auto_fill' => false, 'ai_suggestion' => false, 'searchable' => false, 'show_in_card' => true ],
            [ 'kategori_slug' => 'konut', 'yayin_tipi' => 'Satılık', 'field_slug' => 'asansor', 'field_name' => 'Asansör', 'field_type' => 'boolean', 'field_category' => 'Genel Özellikler', 'field_icon' => '⬆️', 'status' => true, 'required' => false, 'display_order' => 13, 'ai_auto_fill' => false, 'ai_suggestion' => false, 'searchable' => false, 'show_in_card' => false ],
            [ 'kategori_slug' => 'konut', 'yayin_tipi' => 'Satılık', 'field_slug' => 'krediye_uygun', 'field_name' => 'Krediye Uygun', 'field_type' => 'boolean', 'field_category' => 'Genel Özellikler', 'field_icon' => '🏦', 'status' => true, 'required' => false, 'display_order' => 14, 'ai_auto_fill' => false, 'ai_suggestion' => false, 'searchable' => false, 'show_in_card' => false ],
            [ 'kategori_slug' => 'konut', 'yayin_tipi' => 'Kiralık', 'field_slug' => 'depozito', 'field_name' => 'Depozito', 'field_type' => 'price', 'field_category' => 'Genel Özellikler', 'field_icon' => '💰', 'status' => true, 'required' => false, 'display_order' => 10, 'ai_auto_fill' => false, 'ai_suggestion' => false, 'searchable' => false, 'show_in_card' => false ],
            [ 'kategori_slug' => 'konut', 'yayin_tipi' => 'Kiralık', 'field_slug' => 'aidat', 'field_name' => 'Aidat', 'field_type' => 'price', 'field_category' => 'Genel Özellikler', 'field_icon' => '🧾', 'status' => true, 'required' => false, 'display_order' => 11, 'ai_auto_fill' => false, 'ai_suggestion' => false, 'searchable' => false, 'show_in_card' => false ],
            [ 'kategori_slug' => 'konut', 'yayin_tipi' => 'Kiralık', 'field_slug' => 'isitma_tipi', 'field_name' => 'Isıtma Tipi', 'field_type' => 'select', 'field_category' => 'Genel Özellikler', 'field_icon' => '🔥', 'status' => true, 'required' => false, 'display_order' => 12, 'ai_auto_fill' => false, 'ai_suggestion' => false, 'searchable' => false, 'show_in_card' => false, 'field_options' => json_encode(['Doğalgaz','Klima','Sobalı','Merkezi']) ],
            [ 'kategori_slug' => 'konut', 'yayin_tipi' => 'Kiralık', 'field_slug' => 'kisa_donem_uygun', 'field_name' => 'Kısa Dönem Uygun', 'field_type' => 'boolean', 'field_category' => 'Genel Özellikler', 'field_icon' => '📅', 'status' => true, 'required' => false, 'display_order' => 13, 'ai_auto_fill' => false, 'ai_suggestion' => false, 'searchable' => false, 'show_in_card' => false ],
            [ 'kategori_slug' => 'arsa', 'yayin_tipi' => 'Satılık', 'field_slug' => 'imar_durumu', 'field_name' => 'İmarlı', 'field_type' => 'boolean', 'field_category' => 'Genel Özellikler', 'field_icon' => '📐', 'status' => true, 'required' => false, 'display_order' => 10, 'ai_auto_fill' => false, 'ai_suggestion' => false, 'searchable' => false, 'show_in_card' => true ],
            [ 'kategori_slug' => 'arsa', 'yayin_tipi' => 'Satılık', 'field_slug' => 'tapu_hazir', 'field_name' => 'Tapu Hazır', 'field_type' => 'boolean', 'field_category' => 'Genel Özellikler', 'field_icon' => '📄', 'status' => true, 'required' => false, 'display_order' => 11, 'ai_auto_fill' => false, 'ai_suggestion' => false, 'searchable' => false, 'show_in_card' => false ],
            [ 'kategori_slug' => 'arsa', 'yayin_tipi' => 'Satılık', 'field_slug' => 'elektrik', 'field_name' => 'Elektrik', 'field_type' => 'boolean', 'field_category' => 'Genel Özellikler', 'field_icon' => '⚡', 'status' => true, 'required' => false, 'display_order' => 12, 'ai_auto_fill' => false, 'ai_suggestion' => false, 'searchable' => false, 'show_in_card' => false ],
            [ 'kategori_slug' => 'arsa', 'yayin_tipi' => 'Satılık', 'field_slug' => 'su', 'field_name' => 'Su', 'field_type' => 'boolean', 'field_category' => 'Genel Özellikler', 'field_icon' => '🚰', 'status' => true, 'required' => false, 'display_order' => 13, 'ai_auto_fill' => false, 'ai_suggestion' => false, 'searchable' => false, 'show_in_card' => false ],
            [ 'kategori_slug' => 'arsa', 'yayin_tipi' => 'Satılık', 'field_slug' => 'kanalizasyon', 'field_name' => 'Kanalizasyon', 'field_type' => 'boolean', 'field_category' => 'Genel Özellikler', 'field_icon' => '🕳️', 'status' => true, 'required' => false, 'display_order' => 14, 'ai_auto_fill' => false, 'ai_suggestion' => false, 'searchable' => false, 'show_in_card' => false ],
            [ 'kategori_slug' => 'arsa', 'yayin_tipi' => 'Satılık', 'field_slug' => 'yola_cephe', 'field_name' => 'Yola Cephe', 'field_type' => 'boolean', 'field_category' => 'Genel Özellikler', 'field_icon' => '🛣️', 'status' => true, 'required' => false, 'display_order' => 15, 'ai_auto_fill' => false, 'ai_suggestion' => false, 'searchable' => false, 'show_in_card' => false ],
            [ 'kategori_slug' => 'arsa', 'yayin_tipi' => 'Satılık', 'field_slug' => 'parsel_m2', 'field_name' => 'Parsel m²', 'field_type' => 'number', 'field_category' => 'Genel Özellikler', 'field_icon' => '📏', 'status' => true, 'required' => false, 'display_order' => 16, 'ai_auto_fill' => false, 'ai_suggestion' => false, 'searchable' => false, 'show_in_card' => false ],
            [ 'kategori_slug' => 'arsa', 'yayin_tipi' => 'Kiralık', 'field_slug' => 'imar_durumu', 'field_name' => 'İmarlı', 'field_type' => 'boolean', 'field_category' => 'Genel Özellikler', 'field_icon' => '📐', 'status' => true, 'required' => false, 'display_order' => 10, 'ai_auto_fill' => false, 'ai_suggestion' => false, 'searchable' => false, 'show_in_card' => true ],
            [ 'kategori_slug' => 'arsa', 'yayin_tipi' => 'Kiralık', 'field_slug' => 'parsel_m2', 'field_name' => 'Parsel m²', 'field_type' => 'number', 'field_category' => 'Genel Özellikler', 'field_icon' => '📏', 'status' => true, 'required' => false, 'display_order' => 16, 'ai_auto_fill' => false, 'ai_suggestion' => false, 'searchable' => false, 'show_in_card' => false ],
            [ 'kategori_slug' => 'isyeri', 'yayin_tipi' => 'Satılık', 'field_slug' => 'asma_kat', 'field_name' => 'Asma Kat', 'field_type' => 'boolean', 'field_category' => 'Genel Özellikler', 'field_icon' => '🪜', 'status' => true, 'required' => false, 'display_order' => 10, 'ai_auto_fill' => false, 'ai_suggestion' => false, 'searchable' => false, 'show_in_card' => false ],
            [ 'kategori_slug' => 'isyeri', 'yayin_tipi' => 'Satılık', 'field_slug' => 'yuksek_tavan', 'field_name' => 'Yüksek Tavan', 'field_type' => 'boolean', 'field_category' => 'Genel Özellikler', 'field_icon' => '🏗️', 'status' => true, 'required' => false, 'display_order' => 11, 'ai_auto_fill' => false, 'ai_suggestion' => false, 'searchable' => false, 'show_in_card' => false ],
            [ 'kategori_slug' => 'isyeri', 'yayin_tipi' => 'Satılık', 'field_slug' => 'kose_konum', 'field_name' => 'Köşe Konum', 'field_type' => 'boolean', 'field_category' => 'Genel Özellikler', 'field_icon' => '📍', 'status' => true, 'required' => false, 'display_order' => 12, 'ai_auto_fill' => false, 'ai_suggestion' => false, 'searchable' => false, 'show_in_card' => false ],
            [ 'kategori_slug' => 'isyeri', 'yayin_tipi' => 'Satılık', 'field_slug' => 'vitrin', 'field_name' => 'Vitrin', 'field_type' => 'boolean', 'field_category' => 'Genel Özellikler', 'field_icon' => '🪟', 'status' => true, 'required' => false, 'display_order' => 13, 'ai_auto_fill' => false, 'ai_suggestion' => false, 'searchable' => false, 'show_in_card' => false ],
            [ 'kategori_slug' => 'isyeri', 'yayin_tipi' => 'Satılık', 'field_slug' => 'wc', 'field_name' => 'WC', 'field_type' => 'boolean', 'field_category' => 'Genel Özellikler', 'field_icon' => '🚻', 'status' => true, 'required' => false, 'display_order' => 14, 'ai_auto_fill' => false, 'ai_suggestion' => false, 'searchable' => false, 'show_in_card' => false ],
            [ 'kategori_slug' => 'isyeri', 'yayin_tipi' => 'Kiralık', 'field_slug' => 'asma_kat', 'field_name' => 'Asma Kat', 'field_type' => 'boolean', 'field_category' => 'Genel Özellikler', 'field_icon' => '🪜', 'status' => true, 'required' => false, 'display_order' => 10, 'ai_auto_fill' => false, 'ai_suggestion' => false, 'searchable' => false, 'show_in_card' => false ],
            [ 'kategori_slug' => 'isyeri', 'yayin_tipi' => 'Kiralık', 'field_slug' => 'depozito', 'field_name' => 'Depozito', 'field_type' => 'price', 'field_category' => 'Genel Özellikler', 'field_icon' => '💰', 'status' => true, 'required' => false, 'display_order' => 11, 'ai_auto_fill' => false, 'ai_suggestion' => false, 'searchable' => false, 'show_in_card' => false ],
        ];

        foreach ($fields as $data) {
            KategoriYayinTipiFieldDependency::updateOrCreate(
                [
                    'kategori_slug' => $data['kategori_slug'],
                    'yayin_tipi' => $data['yayin_tipi'],
                    'field_slug' => $data['field_slug'],
                ],
                $data
            );
        }
    }
}